[general]
live_config_reload = true

# Import theme, keep this in another file to keep things neat and tidy
import = [
  "~/.config/alacritty/themes/theme.toml"
]

[font]
size = 14

[font.normal]
family = "Source Code Pro ExtraLight"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0002%"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u0022"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u00020"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002o"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[scrolling]
history = 10000

[window]
decorations = "buttonless"
dynamic_padding = false

