# give the terminal window a useful title
set-window-option -g automatic-rename on
set-option -g set-titles on

# disable confirm before killing
bind-key x kill-pane

# enable mouse scrolling
set-option -g mouse on

# [Ctrl-Space] to zoom current pane
# see: https://sgeb.io/posts/tmux-zoom-panes/
bind-key -n C-Space resize-pane -Z

# increase history limit
set-option -g history-limit 100000

# split windows using current path
bind-key '"' split-window -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"
bind-key c new-window -c "#{pane_current_path}"

# configure our status bar
set-option -g status on
set-option -g status-position top
set-option -g status-interval 5
set-option -g status-justify left
set-option -g status-keys emacs
set-option -g status-left ""
set-option -g status-right "#[fg=white,bg=#444444] %H:%M #[fg=white,bg=#666666] %A %-d %B %Y #[fg=white,bg=#999999] #S "
window_status_command_message=' #I:#(~/.config/tmux/shortpath.sh "#{pane_current_path}")###{pane_current_command} '
set-option -g window-status-format "#[fg=white,bg=#444444]$window_status_command_message"
set-option -g window-status-current-format "#[fg=white,bg=#444499]$window_status_command_message#{?window_zoomed_flag,Z ,}"
set-option -g window-status-separator ''
set-option -g status-style fg=colour136,bg=#222222

# reload config with <Leader> + r
unbind-key r
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded …"

# list of plugins
set-option -g @plugin "tmux-plugins/tpm"
set-option -g @plugin "tmux-plugins/tmux-sensible"
set-option -g @plugin "christoomey/vim-tmux-navigator"

set-option -g @plugin "tmux-plugins/tmux-resurrect"
set-option -g @plugin "tmux-plugins/tmux-continuum"
set-option -g @continuum-restore "on"

# initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "/opt/homebrew/opt/tpm/share/tpm/tpm"

